name: 'Upload file to S3'
description: 'Upload file to S3 with metadata'
author: ricardoapaes
branding:
  icon: 'upload'
  color: 'green'
inputs:
  bucket:
    description: 'Name of bucket'
    required: true
  src:
    description: 'File path to upload'
    required: true
  filename:
    description: 'File name within the bucket'
    required: false
  metadata:
    description: 'Metadata of the file to be uploaded.'
    required: false
    default: 'author=like'
  mimetype:
    description: 'Mimetype of the file to be uploaded.'
    required: false
    default: 'application/x-msdownload'
  region:
    description: 'Region where the bucket is located.'
    required: false
    default: 'us-east-1'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ricardoapaes/action-s3-upload:latest'
  args:
    - upload
    - -f ${{ inputs.filename }}
    - -m ${{ inputs.mimetype }}
    - -d ${{ inputs.metadata }}
    - -r ${{ inputs.region }}
    - ${{ inputs.bucket }}
    - ${{ inputs.src }}